"""Data master WCP: 12 dimensi × 3 indikator × 2 item = 72 item.

Sumber: 06_WCP_Survey — Paket Instrumen Kajian Anjab_ABK (CF-3.0 Bagian V).
Data ini statis dan di-seed sekali saat startup; tidak diubah lewat API.
"""

from __future__ import annotations

# (kode, nama, urutan, is_risk)
DIMENSI: list[tuple[str, str, int, bool]] = [
    ("SC", "Stability of Change", 1, False),
    ("TM", "Technology Maturity", 2, False),
    ("AS", "Admin Support", 3, False),
    ("RC", "Role Clarity", 4, False),
    ("DA", "Decision Autonomy", 5, False),
    ("WP", "Workload Predictability", 6, False),
    ("PC", "Peer Collaboration", 7, False),
    ("SS", "Supervisor Support", 8, False),
    ("CH", "Conflict / Harassment", 9, True),
    ("SD", "Student Diversity", 10, True),
    ("PI", "Parent Involvement", 11, True),
    ("RA", "Resource Adequacy", 12, False),
]

# (item_id, kode_dim, indikator_kode, indikator_label, pernyataan, reverse_type, urutan)
# reverse_type: "NONE" | "R" | "UF" | "R_STAR"
ITEM: list[tuple[str, str, str, str, str, str, int]] = [
    # --- SC: Stability of Change ---
    (
        "SC1a",
        "SC",
        "1",
        "Frekuensi perubahan kebijakan",
        "Kebijakan dan prosedur kerja di unit saya berubah terlalu sering sehingga sulit diikuti.",
        "R",
        1,
    ),
    (
        "SC1b",
        "SC",
        "1",
        "Frekuensi perubahan kebijakan",
        "Saya merasa ritme perubahan kebijakan di unit kerja ini berada pada tingkat yang stabil.",
        "NONE",
        2,
    ),
    (
        "SC2a",
        "SC",
        "2",
        "Kecukupan pemberitahuan perubahan",
        "Saya mendapat pemberitahuan yang cukup sebelum ada perubahan kebijakan atau prosedur.",
        "NONE",
        3,
    ),
    (
        "SC2b",
        "SC",
        "2",
        "Kecukupan pemberitahuan perubahan",
        "Pengumuman mengenai perubahan prosedural seringkali dilakukan secara mendadak sehingga"
        " mengganggu rutinitas kerja.",
        "R",
        4,
    ),
    (
        "SC3a",
        "SC",
        "3",
        "Kualitas perencanaan perubahan",
        "Perubahan yang terjadi di unit saya biasanya direncanakan dengan baik.",
        "NONE",
        5,
    ),
    (
        "SC3b",
        "SC",
        "3",
        "Kualitas perencanaan perubahan",
        "Saya merasa seringkali implementasi kebijakan baru dilakukan tanpa persiapan yang matang.",
        "R",
        6,
    ),
    # --- TM: Technology Maturity ---
    (
        "TM1a",
        "TM",
        "1",
        "Efisiensi teknologi",
        "Sistem teknologi yang tersedia membantu saya menyelesaikan pekerjaan lebih efisien.",
        "NONE",
        7,
    ),
    (
        "TM1b",
        "TM",
        "1",
        "Efisiensi teknologi",
        "Penggunaan sistem teknologi yang ada justru memperumit dan memperlambat penyelesaian"
        " tugas saya.",
        "R",
        8,
    ),
    (
        "TM2a",
        "TM",
        "2",
        "Beban manual residual",
        "Saya masih harus mengerjakan banyak hal secara manual yang seharusnya bisa diotomasi.",
        "R",
        9,
    ),
    (
        "TM2b",
        "TM",
        "2",
        "Beban manual residual",
        "Hampir semua tugas rutin administratif saya sudah dikerjakan secara otomatis oleh sistem.",
        "NONE",
        10,
    ),
    (
        "TM3a",
        "TM",
        "3",
        "Integrasi platform",
        "Platform digital yang dipakai di unit saya terintegrasi dengan baik satu sama lain.",
        "NONE",
        11,
    ),
    (
        "TM3b",
        "TM",
        "3",
        "Integrasi platform",
        "Saya merasa kesulitan karena harus berpindah-pindah antar platform digital yang tidak"
        " saling terhubung untuk menyelesaikan satu tugas.",
        "R",
        12,
    ),
    # --- AS: Admin Support ---
    (
        "AS1a",
        "AS",
        "1",
        "Ketersediaan admin support",
        "Ada staf administrasi yang membantu saya sehingga saya bisa fokus pada tugas utama.",
        "NONE",
        13,
    ),
    (
        "AS1b",
        "AS",
        "1",
        "Ketersediaan admin support",
        "Saya merasa sulit untuk mendapatkan bantuan administratif saat sedang sangat dibutuhkan.",
        "R",
        14,
    ),
    (
        "AS2a",
        "AS",
        "2",
        "Admin drift ke guru",
        "Saya sering harus mengerjakan tugas administratif yang seharusnya bukan tanggung jawab"
        " saya.",
        "R",
        15,
    ),
    (
        "AS2b",
        "AS",
        "2",
        "Admin drift ke guru",
        "Saya dapat fokus sepenuhnya pada tugas mengajar/utama saya tanpa diganggu oleh urusan"
        " administratif non-esensial.",
        "NONE",
        16,
    ),
    (
        "AS3a",
        "AS",
        "3",
        "Responsivitas admin",
        "Ketika saya butuh bantuan administratif, bantuan tersebut tersedia dengan cepat.",
        "NONE",
        17,
    ),
    (
        "AS3b",
        "AS",
        "3",
        "Responsivitas admin",
        "Tindak lanjut dari tim administrasi sering kali memakan waktu yang lama (lambat).",
        "R",
        18,
    ),
    # --- RC: Role Clarity ---
    (
        "RC1a",
        "RC",
        "1",
        "Kejelasan ekspektasi",
        "Saya tahu dengan jelas apa yang diharapkan dari jabatan saya.",
        "NONE",
        19,
    ),
    (
        "RC1b",
        "RC",
        "1",
        "Kejelasan ekspektasi",
        "Saya sering merasa bingung mengenai apa sebenarnya standar performa yang diharapkan"
        " atasan dari saya.",
        "R",
        20,
    ),
    (
        "RC2a",
        "RC",
        "2",
        "Ambiguitas batas peran",
        "Batas antara tanggung jawab saya dan rekan lain sering kabur.",
        "R",
        21,
    ),
    (
        "RC2b",
        "RC",
        "2",
        "Ambiguitas batas peran",
        "Ada pembagian tugas yang sangat jelas mengenai siapa yang bertanggung jawab atas suatu"
        " hal antara saya dan rekan kerja lainnya.",
        "NONE",
        22,
    ),
    (
        "RC3a",
        "RC",
        "3",
        "Kesesuaian jobdesc-realitas",
        "Deskripsi pekerjaan formal saya sesuai dengan apa yang benar-benar saya kerjakan.",
        "NONE",
        23,
    ),
    (
        "RC3b",
        "RC",
        "3",
        "Kesesuaian jobdesc-realitas",
        "Deskripsi pekerjaan formal saya saat ini terasa kurang relevan dengan apa yang"
        " sesungguhnya saya kerjakan sehari-hari.",
        "R",
        24,
    ),
    # --- DA: Decision Autonomy ---
    (
        "DA1a",
        "DA",
        "1",
        "Kebebasan metode kerja",
        "Saya memiliki kebebasan yang cukup untuk menentukan cara menyelesaikan pekerjaan saya.",
        "NONE",
        25,
    ),
    (
        "DA1b",
        "DA",
        "1",
        "Kebebasan metode kerja",
        "Saya diharuskan mengikuti prosedur yang sangat kaku dan detail dalam menyelesaikan"
        " tugas saya.",
        "R",
        26,
    ),
    (
        "DA2a",
        "DA",
        "2",
        "Ketergantungan pada approval",
        "Hampir semua keputusan dalam lingkup kerja saya harus mendapat persetujuan atasan.",
        "R",
        27,
    ),
    (
        "DA2b",
        "DA",
        "2",
        "Ketergantungan pada approval",
        "Atasan memberikan kepercayaan penuh (otonomi) kepada saya untuk mengambil keputusan"
        " rutin mengenai pekerjaan.",
        "NONE",
        28,
    ),
    (
        "DA3a",
        "DA",
        "3",
        "Otonomi prioritas",
        "Saya bisa mengatur prioritas kerja saya sendiri dalam batas yang wajar.",
        "NONE",
        29,
    ),
    (
        "DA3b",
        "DA",
        "3",
        "Otonomi prioritas",
        "Saya sering kali tidak dapat menentukan sendiri prioritas kerja saya karena adanya"
        " instruksi eksternal yang mendesak.",
        "R",
        30,
    ),
    # --- WP: Workload Predictability ---
    (
        "WP1a",
        "WP",
        "1",
        "Prediktabilitas beban",
        "Saya bisa memprediksi beban kerja saya dari minggu ke minggu.",
        "NONE",
        31,
    ),
    (
        "WP1b",
        "WP",
        "1",
        "Prediktabilitas beban",
        "Sangat sulit untuk merencanakan waktu kerja karena beban kerja saya sering kali"
        " berfluktuasi secara tidak terduga.",
        "R",
        32,
    ),
    (
        "WP2a",
        "WP",
        "2",
        "Frekuensi tugas mendadak",
        "Saya sering menerima tugas mendadak yang mengacaukan rencana kerja saya.",
        "R",
        33,
    ),
    (
        "WP2b",
        "WP",
        "2",
        "Frekuensi tugas mendadak",
        "Saya jarang sekali mendapatkan tugas-tugas mendadak yang tidak direncanakan sebelumnya.",
        "NONE",
        34,
    ),
    (
        "WP3a",
        "WP",
        "3",
        "Perencanaan jadwal",
        "Jadwal kegiatan di unit saya direncanakan cukup jauh ke depan sehingga saya bisa bersiap.",
        "NONE",
        35,
    ),
    (
        "WP3b",
        "WP",
        "3",
        "Perencanaan jadwal",
        "Saya sering baru diberitahu mengenai agenda penting unit kerja beberapa saat sebelum"
        " acara dimulai (mepet).",
        "R",
        36,
    ),
    # --- PC: Peer Collaboration ---
    (
        "PC1a",
        "PC",
        "1",
        "Berbagi pengetahuan",
        "Rekan kerja saya dan saya saling berbagi pengetahuan dan praktik baik secara rutin.",
        "NONE",
        37,
    ),
    (
        "PC1b",
        "PC",
        "1",
        "Berbagi pengetahuan",
        "Di unit saya, rekan kerja cenderung menyembunyikan informasi penting untuk kepentingan"
        " pribadi.",
        "R",
        38,
    ),
    (
        "PC2a",
        "PC",
        "2",
        "Isolasi kerja",
        "Saya merasa bekerja sendiri tanpa dukungan dari rekan sejawat.",
        "R",
        39,
    ),
    (
        "PC2b",
        "PC",
        "2",
        "Isolasi kerja",
        "Saya merasa menjadi bagian yang integral dari sebuah tim yang solid dan saling mendukung"
        " di unit ini.",
        "NONE",
        40,
    ),
    (
        "PC3a",
        "PC",
        "3",
        "Mekanisme kolaborasi formal",
        "Ada mekanisme kolaborasi formal (PLC, lesson study, dll.) yang berjalan efektif di unit"
        " saya.",
        "NONE",
        41,
    ),
    (
        "PC3b",
        "PC",
        "3",
        "Mekanisme kolaborasi formal",
        "Mekanisme kolaborasi tim yang ada saat ini (PLC, lesson study) terasa kurang efektif"
        " atau kurang bermakna.",
        "R",
        42,
    ),
    # --- SS: Supervisor Support ---
    (
        "SS1a",
        "SS",
        "1",
        "Umpan balik atasan",
        "Atasan langsung saya memberikan umpan balik yang membantu saya berkembang.",
        "NONE",
        43,
    ),
    (
        "SS1b",
        "SS",
        "1",
        "Umpan balik atasan",
        "Umpan balik yang diberikan atasan sering kali tidak konstruktif atau tidak relevan untuk"
        " pengembangan saya.",
        "R",
        44,
    ),
    (
        "SS2a",
        "SS",
        "2",
        "Ketersediaan atasan",
        "Atasan langsung saya jarang tersedia ketika saya butuh bimbingan.",
        "R",
        45,
    ),
    (
        "SS2b",
        "SS",
        "2",
        "Ketersediaan atasan",
        "Pintu atasan saya selalu terbuka bagi saya jika saya membutuhkan diskusi mengenai"
        " masalah pekerjaan.",
        "NONE",
        46,
    ),
    (
        "SS3a",
        "SS",
        "3",
        "Advokasi atasan",
        "Atasan langsung saya secara aktif memperjuangkan kebutuhan sumber daya untuk tim.",
        "NONE",
        47,
    ),
    (
        "SS3b",
        "SS",
        "3",
        "Advokasi atasan",
        "Atasan saya tidak terlalu peduli ketika unit kerja kekurangan sumber daya yang"
        " dibutuhkan tim.",
        "R",
        48,
    ),
    # --- CH: Conflict / Harassment (RISK) ---
    (
        "CH1a",
        "CH",
        "1",
        "Frekuensi konflik",
        "Di unit saya, konflik antar staf sering terjadi dan tidak terkelola dengan baik.",
        "UF",
        49,
    ),
    (
        "CH1b",
        "CH",
        "1",
        "Frekuensi konflik",
        "Ada ketegangan interpersonal yang terjadi secara terus-menerus di lingkungan kerja saya.",
        "UF",
        50,
    ),
    (
        "CH2a",
        "CH",
        "2",
        "Keamanan psikologis menyampaikan pendapat",
        "Saya merasa aman untuk menyampaikan pendapat berbeda tanpa takut konsekuensi negatif.",
        "R_STAR",
        51,
    ),
    (
        "CH2b",
        "CH",
        "2",
        "Keamanan psikologis menyampaikan pendapat",
        "Saya merasa takut atau ragu untuk menyuarakan ketidaksetujuan atau kekhawatiran saya"
        " di hadapan atasan.",
        "UF",
        52,
    ),
    (
        "CH3a",
        "CH",
        "3",
        "Pengalaman perlakuan tidak adil",
        "Pernah ada situasi di mana saya atau rekan merasa diperlakukan tidak adil atau tidak"
        " menyenangkan.",
        "UF",
        53,
    ),
    (
        "CH3b",
        "CH",
        "3",
        "Pengalaman perlakuan tidak adil",
        "Saya melihat adanya contoh favoritisme (pilih kasih) yang dilakukan oleh manajemen di"
        " unit ini.",
        "UF",
        54,
    ),
    # --- SD: Student Diversity (RISK) ---
    (
        "SD1a",
        "SD",
        "1",
        "Kompleksitas keragaman murid",
        "Murid di kelas saya memiliki kebutuhan belajar yang sangat beragam sehingga menambah"
        " kompleksitas mengajar.",
        "UF",
        55,
    ),
    (
        "SD1b",
        "SD",
        "1",
        "Kompleksitas keragaman murid",
        "Rentang kemampuan akademik murid di dalam satu kelas yang sama terlalu lebar untuk"
        " ditangani secara efektif.",
        "UF",
        56,
    ),
    (
        "SD2a",
        "SD",
        "2",
        "Kecukupan dukungan untuk keragaman",
        "Saya memiliki cukup dukungan (tools, pelatihan, asisten) untuk menangani keragaman murid.",
        "R_STAR",
        57,
    ),
    (
        "SD2b",
        "SD",
        "2",
        "Kecukupan dukungan untuk keragaman",
        "Saya tidak mendapatkan pelatihan atau bimbingan yang memadai dari lembaga untuk"
        " menangani keragaman murid.",
        "UF",
        58,
    ),
    (
        "SD3a",
        "SD",
        "3",
        "Dampak perilaku murid pada waktu",
        "Perilaku murid yang menantang menghabiskan porsi signifikan waktu mengajar saya.",
        "UF",
        59,
    ),
    (
        "SD3b",
        "SD",
        "3",
        "Dampak perilaku murid pada waktu",
        "Saya sering merasa stres karena porsi besar waktu saya di kelas dihabiskan untuk"
        " mendisiplinkan murid daripada mengajar.",
        "UF",
        60,
    ),
    # --- PI: Parent Involvement (RISK) ---
    (
        "PI1a",
        "PI",
        "1",
        "Intrusi komunikasi ortu",
        "Orang tua murid sering menghubungi saya di luar jam kerja untuk hal-hal yang seharusnya"
        " bisa ditangani melalui jalur formal.",
        "UF",
        61,
    ),
    (
        "PI1b",
        "PI",
        "1",
        "Intrusi komunikasi ortu",
        "Saya merasa terus dihubungi oleh orang tua murid di luar jam kerja saya, mengganggu"
        " waktu istirahat saya.",
        "UF",
        62,
    ),
    (
        "PI2a",
        "PI",
        "2",
        "Keterkelolaan komunikasi ortu",
        "Komunikasi dengan orang tua terkelola baik melalui sistem yang jelas.",
        "R_STAR",
        63,
    ),
    (
        "PI2b",
        "PI",
        "2",
        "Keterkelolaan komunikasi ortu",
        "Interaksi dengan orang tua sering kali tidak terorganisir dengan baik dan menyita waktu"
        " pribadi saya.",
        "UF",
        64,
    ),
    (
        "PI3a",
        "PI",
        "3",
        "Beban tuntutan/komplain ortu",
        "Tuntutan atau komplain dari orang tua menambah beban kerja saya secara signifikan.",
        "UF",
        65,
    ),
    (
        "PI3b",
        "PI",
        "3",
        "Beban tuntutan/komplain ortu",
        "Saya sering dihadapkan pada komplain atau tuntutan yang tidak realistis dari orang tua"
        " murid terkait nilai atau perlakuan anak.",
        "UF",
        66,
    ),
    # --- RA: Resource Adequacy ---
    (
        "RA1a",
        "RA",
        "1",
        "Akses fasilitas dan alat",
        "Saya memiliki akses yang cukup ke ruang, alat, dan bahan yang dibutuhkan untuk bekerja.",
        "NONE",
        67,
    ),
    (
        "RA1b",
        "RA",
        "1",
        "Akses fasilitas dan alat",
        "Saya merasa kesulitan untuk mengakses ruang kelas, alat bantu mengajar, atau laboratorium"
        " saat sangat dibutuhkan.",
        "R",
        68,
    ),
    (
        "RA2a",
        "RA",
        "2",
        "Hambatan anggaran",
        "Keterbatasan anggaran sering menghambat saya menjalankan program atau kegiatan yang"
        " diperlukan.",
        "R",
        69,
    ),
    (
        "RA2b",
        "RA",
        "2",
        "Hambatan anggaran",
        "Lembaga ini menyediakan dana taktis yang memadai untuk mendukung program-program baru"
        " di unit saya.",
        "NONE",
        70,
    ),
    (
        "RA3a",
        "RA",
        "3",
        "Kondisi infrastruktur",
        "Infrastruktur fisik tempat saya bekerja (ruang kelas, laboratorium, dll.) dalam kondisi"
        " yang memadai.",
        "NONE",
        71,
    ),
    (
        "RA3b",
        "RA",
        "3",
        "Kondisi infrastruktur",
        "Kondisi fisik fasilitas kerja saya (ruang kelas, kantor, furniture) sering kali dalam"
        " kondisi kurang layak atau rusak.",
        "R",
        72,
    ),
]
