"""fk cascade sesi responden jawaban

Revision ID: a4aeb5bcbe81
Revises: 0a58616358f4
Create Date: 2026-07-12 02:26:17.261177

Menambahkan FK `ON DELETE CASCADE` di 12 kolom `sesi_id`/`responden_id` (DCS, WCP,
OPM, Task Inventory) yang sebelumnya hanya `String(40)` tanpa constraint — menghapus
sesi/responden lewat API meninggalkan baris anak YATIM yang tak terjangkau API mana
pun. Sekaligus menambal bug tak terlaporkan: `responden_sql.py::delete()` (DCS/WCP/
OPM/TI) menghapus responden tanpa menghapus jawabannya.

Sebelum membuat FK, baris yatim yang SUDAH ADA (dari penghapusan sesi/responden lewat
API sebelum revisi ini) dibersihkan dulu — bila tidak, `create_foreign_key` akan gagal
karena data melanggar constraint. Urutan pembersihan PENTING:
1. Hapus responden yatim (sesi induknya sudah hilang) — langkah ini melahirkan
   jawaban/seleksi/detail yatim BARU (induk respondennya baru saja hilang).
2. Hapus jawaban/seleksi/detail/tahap2 yatim — menjaring juga anak dari langkah 1
   sekaligus baris yang sudah yatim sebelumnya.
3. Baru buat FK `ON DELETE CASCADE`.

Downgrade hanya melepas FK — baris yatim yang terhapus di `upgrade()` TIDAK
direkonstruksi (tidak ada cara merekonstruksi data yang sudah dihapus).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a4aeb5bcbe81"
down_revision: str | None = "0a58616358f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _delete_orphans(connection: sa.engine.Connection, child: str, col: str, parent: str) -> None:
    connection.execute(
        sa.text(
            f"""
            DELETE FROM {child} c
            WHERE NOT EXISTS (SELECT 1 FROM {parent} p WHERE p.id = c.{col})
            """
        )
    )


def upgrade() -> None:
    connection = op.get_bind()

    # 1) Responden yatim (sesi induk sudah hilang).
    _delete_orphans(connection, "dcs_responden", "sesi_id", "dcs_sesi")
    _delete_orphans(connection, "wcp_responden", "sesi_id", "wcp_sesi")
    _delete_orphans(connection, "opm_responden", "sesi_id", "opm_sesi")
    _delete_orphans(connection, "ti_responden", "sesi_id", "ti_sesi")

    # 2) Jawaban/seleksi/detail/tahap2 yatim — termasuk anak dari langkah 1.
    _delete_orphans(connection, "dcs_jawaban", "responden_id", "dcs_responden")
    _delete_orphans(connection, "wcp_jawaban", "responden_id", "wcp_responden")
    _delete_orphans(connection, "opm_jawaban", "responden_id", "opm_responden")
    _delete_orphans(connection, "ti_seleksi", "responden_id", "ti_responden")
    _delete_orphans(connection, "ti_seleksi", "sesi_id", "ti_sesi")
    _delete_orphans(connection, "ti_detail", "responden_id", "ti_responden")
    _delete_orphans(connection, "ti_detail", "sesi_id", "ti_sesi")
    _delete_orphans(connection, "ti_tahap2", "sesi_id", "ti_sesi")

    # 3) FK ON DELETE CASCADE.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_dcs_jawaban_responden_id_dcs_responden"),
        "dcs_jawaban",
        "dcs_responden",
        ["responden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_dcs_responden_sesi_id_dcs_sesi"),
        "dcs_responden",
        "dcs_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_opm_jawaban_responden_id_opm_responden"),
        "opm_jawaban",
        "opm_responden",
        ["responden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_opm_responden_sesi_id_opm_sesi"),
        "opm_responden",
        "opm_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_detail_responden_id_ti_responden"),
        "ti_detail",
        "ti_responden",
        ["responden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_detail_sesi_id_ti_sesi"),
        "ti_detail",
        "ti_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_responden_sesi_id_ti_sesi"),
        "ti_responden",
        "ti_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_seleksi_sesi_id_ti_sesi"),
        "ti_seleksi",
        "ti_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_seleksi_responden_id_ti_responden"),
        "ti_seleksi",
        "ti_responden",
        ["responden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_ti_tahap2_sesi_id_ti_sesi"),
        "ti_tahap2",
        "ti_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_wcp_jawaban_responden_id_wcp_responden"),
        "wcp_jawaban",
        "wcp_responden",
        ["responden_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_wcp_responden_sesi_id_wcp_sesi"),
        "wcp_responden",
        "wcp_sesi",
        ["sesi_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_wcp_responden_sesi_id_wcp_sesi"), "wcp_responden", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_wcp_jawaban_responden_id_wcp_responden"), "wcp_jawaban", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_ti_tahap2_sesi_id_ti_sesi"), "ti_tahap2", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_ti_seleksi_responden_id_ti_responden"), "ti_seleksi", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_ti_seleksi_sesi_id_ti_sesi"), "ti_seleksi", type_="foreignkey")
    op.drop_constraint(op.f("fk_ti_responden_sesi_id_ti_sesi"), "ti_responden", type_="foreignkey")
    op.drop_constraint(op.f("fk_ti_detail_sesi_id_ti_sesi"), "ti_detail", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_ti_detail_responden_id_ti_responden"), "ti_detail", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_opm_responden_sesi_id_opm_sesi"), "opm_responden", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_opm_jawaban_responden_id_opm_responden"), "opm_jawaban", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_dcs_responden_sesi_id_dcs_sesi"), "dcs_responden", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_dcs_jawaban_responden_id_dcs_responden"), "dcs_jawaban", type_="foreignkey"
    )
    # ### end Alembic commands ###
