"""tambah nilai standar OPM ke katalog TI

Revision ID: c8fb8be9e184
Revises: 3889bd9af66e
Create Date: 2026-07-29 02:30:43.892803

Backlog `anjab-abk-backend#33`. Murni DDL — tiga kolom baru pada
`ti_uraian_tugas_jabatan`: `std_opm_importance`, `std_opm_frequency`,
`std_opm_criticality` (`Integer`, nullable, tanpa server default). Prefiks `std_opm_`
membedakannya dari `std_frekuensi_teks` yang bermakna beda (frekuensi teks bebas untuk
ABK). Backfill nilai untuk baris existing ada di revisi data terpisah yang mengikuti
revisi ini (`c8fb8be9e184` -> data migration berikutnya), mengikuti disiplin migrasi
repo ini: satu revisi = satu perubahan struktur, backfill dipisah dari DDL.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c8fb8be9e184"
down_revision: str | None = "3889bd9af66e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ti_uraian_tugas_jabatan", sa.Column("std_opm_importance", sa.Integer(), nullable=True)
    )
    op.add_column(
        "ti_uraian_tugas_jabatan", sa.Column("std_opm_frequency", sa.Integer(), nullable=True)
    )
    op.add_column(
        "ti_uraian_tugas_jabatan", sa.Column("std_opm_criticality", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ti_uraian_tugas_jabatan", "std_opm_criticality")
    op.drop_column("ti_uraian_tugas_jabatan", "std_opm_frequency")
    op.drop_column("ti_uraian_tugas_jabatan", "std_opm_importance")
    # ### end Alembic commands ###
