"""ubah std_durasi_per_kali jadi teks bebas

Revision ID: 1be8921ba27b
Revises: 0c932069e90e
Create Date: 2026-07-12 09:05:07.223647
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1be8921ba27b"
down_revision: str | None = "0c932069e90e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ti_uraian_tugas",
        "std_durasi_per_kali",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # postgresql_using wajib: varchar -> integer bukan assignment cast di Postgres.
    # Nilai non-numerik (mis. "Bervariasi", "<2 jam") tidak bisa direpresentasikan
    # sebagai Integer — downgrade ini lossy by design, dibulatkan jadi NULL.
    op.alter_column(
        "ti_uraian_tugas",
        "std_durasi_per_kali",
        existing_type=sa.String(length=100),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using=(
            "CASE WHEN std_durasi_per_kali ~ '^[0-9]+$' "
            "THEN std_durasi_per_kali::integer ELSE NULL END"
        ),
    )
