"""initial schema

Revision ID: b2bbd3afbe65
Revises:
Create Date: 2026-06-23 10:32:25.688655
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b2bbd3afbe65"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dcs_item",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=20), nullable=False),
        sa.Column("subskala_kode", sa.String(length=20), nullable=False),
        sa.Column("sub_dimensi", sa.String(length=150), nullable=False),
        sa.Column("pernyataan", sa.Text(), nullable=False),
        sa.Column("arah", sa.String(length=4), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcs_item")),
        sa.UniqueConstraint("item_id", name=op.f("uq_dcs_item_item_id")),
    )
    op.create_index(op.f("ix_dcs_item_subskala_kode"), "dcs_item", ["subskala_kode"], unique=False)
    op.create_table(
        "dcs_jawaban",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=20), nullable=False),
        sa.Column("skor_raw", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcs_jawaban")),
        sa.UniqueConstraint("responden_id", "item_id", name=op.f("uq_dcs_jawaban_responden_id")),
    )
    op.create_index(
        op.f("ix_dcs_jawaban_responden_id"), "dcs_jawaban", ["responden_id"], unique=False
    )
    op.create_table(
        "dcs_responden",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=True),
        sa.Column("jabatan_label", sa.String(length=200), nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=True),
        sa.Column("sudah_submit", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcs_responden")),
    )
    op.create_index(
        op.f("ix_dcs_responden_created_at"), "dcs_responden", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_dcs_responden_partisipan_id"), "dcs_responden", ["partisipan_id"], unique=False
    )
    op.create_index(op.f("ix_dcs_responden_sesi_id"), "dcs_responden", ["sesi_id"], unique=False)
    op.create_table(
        "dcs_sesi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("periode", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("min_responden", sa.Integer(), nullable=False),
        sa.Column("max_responden", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcs_sesi")),
    )
    op.create_index(op.f("ix_dcs_sesi_created_at"), "dcs_sesi", ["created_at"], unique=False)
    op.create_table(
        "dcs_subskala",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=20), nullable=False),
        sa.Column("nama", sa.String(length=150), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dcs_subskala")),
        sa.UniqueConstraint("kode", name=op.f("uq_dcs_subskala_kode")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_idempotency_keys")),
    )
    op.create_table(
        "jabatan",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=30), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=False),
        sa.Column("jenis", sa.String(length=20), nullable=False),
        sa.Column("unit_kerja_id", sa.String(length=40), nullable=True),
        sa.Column("deskripsi", sa.Text(), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jabatan")),
        sa.UniqueConstraint("kode", name=op.f("uq_jabatan_kode")),
    )
    op.create_index(op.f("ix_jabatan_created_at"), "jabatan", ["created_at"], unique=False)
    op.create_index(op.f("ix_jabatan_unit_kerja_id"), "jabatan", ["unit_kerja_id"], unique=False)
    op.create_table(
        "jenjang_pendidikan",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=50), nullable=False),
        sa.Column("nama", sa.String(length=150), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jenjang_pendidikan")),
        sa.UniqueConstraint("kode", name=op.f("uq_jenjang_pendidikan_kode")),
    )
    op.create_table(
        "mata_pelajaran",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=50), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=False),
        sa.Column("kelompok", sa.String(length=30), nullable=False),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("deskripsi", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mata_pelajaran")),
        sa.UniqueConstraint("kode", name=op.f("uq_mata_pelajaran_kode")),
    )
    op.create_table(
        "partisipan",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("sekolah_id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_utama_id", sa.String(length=40), nullable=False),
        sa.Column("masa_kerja_tahun", sa.Integer(), nullable=False),
        sa.Column("masa_kerja_bulan", sa.Integer(), nullable=False),
        sa.Column("mata_pelajaran_utama_id", sa.String(length=40), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("authentik_user_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partisipan")),
    )
    op.create_index(
        op.f("ix_partisipan_authentik_user_id"), "partisipan", ["authentik_user_id"], unique=False
    )
    op.create_index(op.f("ix_partisipan_created_at"), "partisipan", ["created_at"], unique=False)
    op.create_index(op.f("ix_partisipan_email"), "partisipan", ["email"], unique=False)
    op.create_index(
        op.f("ix_partisipan_jabatan_utama_id"), "partisipan", ["jabatan_utama_id"], unique=False
    )
    op.create_index(op.f("ix_partisipan_sekolah_id"), "partisipan", ["sekolah_id"], unique=False)
    op.create_table(
        "sekolah",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=False),
        sa.Column("jenjang_pendidikan_id", sa.String(length=40), nullable=False),
        sa.Column("npsn", sa.String(length=8), nullable=True),
        sa.Column("kota", sa.String(length=100), nullable=True),
        sa.Column("provinsi", sa.String(length=100), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sekolah")),
        sa.UniqueConstraint("npsn", name=op.f("uq_sekolah_npsn")),
    )
    op.create_index(op.f("ix_sekolah_created_at"), "sekolah", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_sekolah_jenjang_pendidikan_id"), "sekolah", ["jenjang_pendidikan_id"], unique=False
    )
    op.create_table(
        "sme_panel",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("koordinator_id", sa.String(length=40), nullable=True),
        sa.Column("aktif", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sme_panel")),
        sa.UniqueConstraint("jabatan_id", name=op.f("uq_sme_panel_jabatan_id")),
    )
    op.create_index(op.f("ix_sme_panel_created_at"), "sme_panel", ["created_at"], unique=False)
    op.create_table(
        "ti_detail",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.Column("sumber_bukti", sa.String(length=20), nullable=False),
        sa.Column("kondisi", sa.String(length=20), nullable=False),
        sa.Column("frekuensi_teks", sa.String(length=100), nullable=False),
        sa.Column("durasi_per_kali", sa.Integer(), nullable=False),
        sa.Column("jam_per_minggu", sa.Float(), nullable=False),
        sa.Column("peak4w_hours", sa.Float(), nullable=False),
        sa.Column("ai_mode", sa.String(length=20), nullable=False),
        sa.Column("va_type", sa.String(length=20), nullable=False),
        sa.Column("dcs_flag", sa.Boolean(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_detail")),
    )
    op.create_index(op.f("ix_ti_detail_created_at"), "ti_detail", ["created_at"], unique=False)
    op.create_index(op.f("ix_ti_detail_responden_id"), "ti_detail", ["responden_id"], unique=False)
    op.create_index(op.f("ix_ti_detail_sesi_id"), "ti_detail", ["sesi_id"], unique=False)
    op.create_table(
        "ti_detil_tugas",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=300), nullable=False),
        sa.Column("tugas_pokok_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_detil_tugas")),
    )
    op.create_index(
        op.f("ix_ti_detil_tugas_created_at"), "ti_detil_tugas", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ti_detil_tugas_tugas_pokok_id"), "ti_detil_tugas", ["tugas_pokok_id"], unique=False
    )
    op.create_table(
        "ti_responden",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=True),
        sa.Column("partisipan_id", sa.String(length=40), nullable=True),
        sa.Column("tahap1_submit", sa.Boolean(), nullable=False),
        sa.Column("tahap1_submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tahap3_submit", sa.Boolean(), nullable=False),
        sa.Column("tahap3_submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_responden")),
    )
    op.create_index(
        op.f("ix_ti_responden_created_at"), "ti_responden", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ti_responden_partisipan_id"), "ti_responden", ["partisipan_id"], unique=False
    )
    op.create_index(op.f("ix_ti_responden_sesi_id"), "ti_responden", ["sesi_id"], unique=False)
    op.create_table(
        "ti_seleksi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_seleksi")),
    )
    op.create_index(
        op.f("ix_ti_seleksi_responden_id"), "ti_seleksi", ["responden_id"], unique=False
    )
    op.create_index(op.f("ix_ti_seleksi_sesi_id"), "ti_seleksi", ["sesi_id"], unique=False)
    op.create_table(
        "ti_sesi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=True),
        sa.Column("periode", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("koordinator_id", sa.String(length=40), nullable=True),
        sa.Column("min_responden", sa.Integer(), nullable=False),
        sa.Column("max_responden", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("task_frozen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_sesi")),
    )
    op.create_index(op.f("ix_ti_sesi_created_at"), "ti_sesi", ["created_at"], unique=False)
    op.create_index(op.f("ix_ti_sesi_jabatan_id"), "ti_sesi", ["jabatan_id"], unique=False)
    op.create_table(
        "ti_tahap2",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.Column("disetujui", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_tahap2")),
        sa.UniqueConstraint("sesi_id", "task_kode", name=op.f("uq_ti_tahap2_sesi_id")),
    )
    op.create_index(op.f("ix_ti_tahap2_sesi_id"), "ti_tahap2", ["sesi_id"], unique=False)
    op.create_table(
        "ti_tugas_pokok",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_tugas_pokok")),
        sa.UniqueConstraint("nama", name=op.f("uq_ti_tugas_pokok_nama")),
    )
    op.create_index(
        op.f("ix_ti_tugas_pokok_created_at"), "ti_tugas_pokok", ["created_at"], unique=False
    )
    op.create_table(
        "ti_uraian_tugas",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=20), nullable=False),
        sa.Column("uraian", sa.Text(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.Column("tugas_pokok_id", sa.String(length=40), nullable=False),
        sa.Column("detil_tugas_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_uraian_tugas")),
        sa.UniqueConstraint("kode", name=op.f("uq_ti_uraian_tugas_kode")),
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_created_at"), "ti_uraian_tugas", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_detil_tugas_id"),
        "ti_uraian_tugas",
        ["detil_tugas_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_id"), "ti_uraian_tugas", ["jabatan_id"], unique=False
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_tugas_pokok_id"),
        "ti_uraian_tugas",
        ["tugas_pokok_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ti_uraian_tugas_unit"), "ti_uraian_tugas", ["unit"], unique=False)
    op.create_table(
        "ts_log",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("tanggal", sa.Date(), nullable=False),
        sa.Column("waktu_masuk", sa.String(length=5), nullable=False),
        sa.Column("waktu_keluar", sa.String(length=5), nullable=False),
        sa.Column("day_color", sa.String(length=10), nullable=False),
        sa.Column("menit_core", sa.Integer(), nullable=False),
        sa.Column("menit_character", sa.Integer(), nullable=False),
        sa.Column("menit_improve", sa.Integer(), nullable=False),
        sa.Column("menit_strategic", sa.Integer(), nullable=False),
        sa.Column("menit_admin", sa.Integer(), nullable=False),
        sa.Column("menit_recovery", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ts_log")),
        sa.UniqueConstraint("responden_id", "tanggal", name=op.f("uq_ts_log_responden_id")),
    )
    op.create_index(op.f("ix_ts_log_responden_id"), "ts_log", ["responden_id"], unique=False)
    op.create_table(
        "ts_responden",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=True),
        sa.Column("jabatan_label", sa.String(length=200), nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ts_responden")),
    )
    op.create_index(
        op.f("ix_ts_responden_created_at"), "ts_responden", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ts_responden_partisipan_id"), "ts_responden", ["partisipan_id"], unique=False
    )
    op.create_index(op.f("ix_ts_responden_sesi_id"), "ts_responden", ["sesi_id"], unique=False)
    op.create_table(
        "ts_sesi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("periode", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ts_sesi")),
    )
    op.create_index(op.f("ix_ts_sesi_created_at"), "ts_sesi", ["created_at"], unique=False)
    op.create_index(op.f("ix_ts_sesi_jabatan_id"), "ts_sesi", ["jabatan_id"], unique=False)
    op.create_table(
        "wcp_dimensi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=20), nullable=False),
        sa.Column("nama", sa.String(length=150), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.Column("is_risk", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wcp_dimensi")),
        sa.UniqueConstraint("kode", name=op.f("uq_wcp_dimensi_kode")),
    )
    op.create_table(
        "wcp_item",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=20), nullable=False),
        sa.Column("dimensi_kode", sa.String(length=20), nullable=False),
        sa.Column("indikator_kode", sa.String(length=20), nullable=False),
        sa.Column("indikator_label", sa.String(length=200), nullable=False),
        sa.Column("pernyataan", sa.Text(), nullable=False),
        sa.Column("reverse_type", sa.String(length=10), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wcp_item")),
        sa.UniqueConstraint("item_id", name=op.f("uq_wcp_item_item_id")),
    )
    op.create_index(op.f("ix_wcp_item_dimensi_kode"), "wcp_item", ["dimensi_kode"], unique=False)
    op.create_table(
        "wcp_jawaban",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("item_id", sa.String(length=20), nullable=False),
        sa.Column("skor_raw", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wcp_jawaban")),
        sa.UniqueConstraint("responden_id", "item_id", name=op.f("uq_wcp_jawaban_responden_id")),
    )
    op.create_index(
        op.f("ix_wcp_jawaban_responden_id"), "wcp_jawaban", ["responden_id"], unique=False
    )
    op.create_table(
        "wcp_responden",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=True),
        sa.Column("jabatan_label", sa.String(length=200), nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=True),
        sa.Column("sudah_submit", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wcp_responden")),
    )
    op.create_index(
        op.f("ix_wcp_responden_created_at"), "wcp_responden", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_wcp_responden_partisipan_id"), "wcp_responden", ["partisipan_id"], unique=False
    )
    op.create_index(op.f("ix_wcp_responden_sesi_id"), "wcp_responden", ["sesi_id"], unique=False)
    op.create_table(
        "wcp_sesi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("periode", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("min_responden", sa.Integer(), nullable=False),
        sa.Column("max_responden", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wcp_sesi")),
    )
    op.create_index(op.f("ix_wcp_sesi_created_at"), "wcp_sesi", ["created_at"], unique=False)
    op.create_table(
        "partisipan_jabatan_tambahan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["partisipan_id"],
            ["partisipan.id"],
            name=op.f("fk_partisipan_jabatan_tambahan_partisipan_id_partisipan"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partisipan_jabatan_tambahan")),
        sa.UniqueConstraint(
            "partisipan_id", "jabatan_id", name=op.f("uq_partisipan_jabatan_tambahan_partisipan_id")
        ),
    )
    op.create_index(
        op.f("ix_partisipan_jabatan_tambahan_partisipan_id"),
        "partisipan_jabatan_tambahan",
        ["partisipan_id"],
        unique=False,
    )
    op.create_table(
        "sme_panel_anggota",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(length=40), nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["sme_panel.id"],
            name=op.f("fk_sme_panel_anggota_panel_id_sme_panel"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sme_panel_anggota")),
        sa.UniqueConstraint(
            "panel_id", "partisipan_id", name=op.f("uq_sme_panel_anggota_panel_id")
        ),
    )
    op.create_index(
        op.f("ix_sme_panel_anggota_panel_id"), "sme_panel_anggota", ["panel_id"], unique=False
    )
    op.create_table(
        "ti_detil_tugas_jabatan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("detil_tugas_id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["detil_tugas_id"],
            ["ti_detil_tugas.id"],
            name=op.f("fk_ti_detil_tugas_jabatan_detil_tugas_id_ti_detil_tugas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_detil_tugas_jabatan")),
        sa.UniqueConstraint(
            "detil_tugas_id", "jabatan_id", name=op.f("uq_ti_detil_tugas_jabatan_detil_tugas_id")
        ),
    )
    op.create_index(
        op.f("ix_ti_detil_tugas_jabatan_detil_tugas_id"),
        "ti_detil_tugas_jabatan",
        ["detil_tugas_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_detil_tugas_jabatan_jabatan_id"),
        "ti_detil_tugas_jabatan",
        ["jabatan_id"],
        unique=False,
    )
    op.create_table(
        "ti_sesi_task_terpilih",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesi_id"],
            ["ti_sesi.id"],
            name=op.f("fk_ti_sesi_task_terpilih_sesi_id_ti_sesi"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_sesi_task_terpilih")),
        sa.UniqueConstraint("sesi_id", "task_kode", name=op.f("uq_ti_sesi_task_terpilih_sesi_id")),
    )
    op.create_index(
        op.f("ix_ti_sesi_task_terpilih_sesi_id"), "ti_sesi_task_terpilih", ["sesi_id"], unique=False
    )
    op.create_table(
        "ti_tugas_pokok_jabatan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tugas_pokok_id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["tugas_pokok_id"],
            ["ti_tugas_pokok.id"],
            name=op.f("fk_ti_tugas_pokok_jabatan_tugas_pokok_id_ti_tugas_pokok"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_tugas_pokok_jabatan")),
        sa.UniqueConstraint(
            "tugas_pokok_id", "jabatan_id", name=op.f("uq_ti_tugas_pokok_jabatan_tugas_pokok_id")
        ),
    )
    op.create_index(
        op.f("ix_ti_tugas_pokok_jabatan_jabatan_id"),
        "ti_tugas_pokok_jabatan",
        ["jabatan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_tugas_pokok_jabatan_tugas_pokok_id"),
        "ti_tugas_pokok_jabatan",
        ["tugas_pokok_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ti_tugas_pokok_jabatan_tugas_pokok_id"), table_name="ti_tugas_pokok_jabatan"
    )
    op.drop_index(op.f("ix_ti_tugas_pokok_jabatan_jabatan_id"), table_name="ti_tugas_pokok_jabatan")
    op.drop_table("ti_tugas_pokok_jabatan")
    op.drop_index(op.f("ix_ti_sesi_task_terpilih_sesi_id"), table_name="ti_sesi_task_terpilih")
    op.drop_table("ti_sesi_task_terpilih")
    op.drop_index(op.f("ix_ti_detil_tugas_jabatan_jabatan_id"), table_name="ti_detil_tugas_jabatan")
    op.drop_index(
        op.f("ix_ti_detil_tugas_jabatan_detil_tugas_id"), table_name="ti_detil_tugas_jabatan"
    )
    op.drop_table("ti_detil_tugas_jabatan")
    op.drop_index(op.f("ix_sme_panel_anggota_panel_id"), table_name="sme_panel_anggota")
    op.drop_table("sme_panel_anggota")
    op.drop_index(
        op.f("ix_partisipan_jabatan_tambahan_partisipan_id"),
        table_name="partisipan_jabatan_tambahan",
    )
    op.drop_table("partisipan_jabatan_tambahan")
    op.drop_index(op.f("ix_wcp_sesi_created_at"), table_name="wcp_sesi")
    op.drop_table("wcp_sesi")
    op.drop_index(op.f("ix_wcp_responden_sesi_id"), table_name="wcp_responden")
    op.drop_index(op.f("ix_wcp_responden_partisipan_id"), table_name="wcp_responden")
    op.drop_index(op.f("ix_wcp_responden_created_at"), table_name="wcp_responden")
    op.drop_table("wcp_responden")
    op.drop_index(op.f("ix_wcp_jawaban_responden_id"), table_name="wcp_jawaban")
    op.drop_table("wcp_jawaban")
    op.drop_index(op.f("ix_wcp_item_dimensi_kode"), table_name="wcp_item")
    op.drop_table("wcp_item")
    op.drop_table("wcp_dimensi")
    op.drop_index(op.f("ix_ts_sesi_jabatan_id"), table_name="ts_sesi")
    op.drop_index(op.f("ix_ts_sesi_created_at"), table_name="ts_sesi")
    op.drop_table("ts_sesi")
    op.drop_index(op.f("ix_ts_responden_sesi_id"), table_name="ts_responden")
    op.drop_index(op.f("ix_ts_responden_partisipan_id"), table_name="ts_responden")
    op.drop_index(op.f("ix_ts_responden_created_at"), table_name="ts_responden")
    op.drop_table("ts_responden")
    op.drop_index(op.f("ix_ts_log_responden_id"), table_name="ts_log")
    op.drop_table("ts_log")
    op.drop_index(op.f("ix_ti_uraian_tugas_unit"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_tugas_pokok_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_jabatan_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_detil_tugas_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_created_at"), table_name="ti_uraian_tugas")
    op.drop_table("ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_tugas_pokok_created_at"), table_name="ti_tugas_pokok")
    op.drop_table("ti_tugas_pokok")
    op.drop_index(op.f("ix_ti_tahap2_sesi_id"), table_name="ti_tahap2")
    op.drop_table("ti_tahap2")
    op.drop_index(op.f("ix_ti_sesi_jabatan_id"), table_name="ti_sesi")
    op.drop_index(op.f("ix_ti_sesi_created_at"), table_name="ti_sesi")
    op.drop_table("ti_sesi")
    op.drop_index(op.f("ix_ti_seleksi_sesi_id"), table_name="ti_seleksi")
    op.drop_index(op.f("ix_ti_seleksi_responden_id"), table_name="ti_seleksi")
    op.drop_table("ti_seleksi")
    op.drop_index(op.f("ix_ti_responden_sesi_id"), table_name="ti_responden")
    op.drop_index(op.f("ix_ti_responden_partisipan_id"), table_name="ti_responden")
    op.drop_index(op.f("ix_ti_responden_created_at"), table_name="ti_responden")
    op.drop_table("ti_responden")
    op.drop_index(op.f("ix_ti_detil_tugas_tugas_pokok_id"), table_name="ti_detil_tugas")
    op.drop_index(op.f("ix_ti_detil_tugas_created_at"), table_name="ti_detil_tugas")
    op.drop_table("ti_detil_tugas")
    op.drop_index(op.f("ix_ti_detail_sesi_id"), table_name="ti_detail")
    op.drop_index(op.f("ix_ti_detail_responden_id"), table_name="ti_detail")
    op.drop_index(op.f("ix_ti_detail_created_at"), table_name="ti_detail")
    op.drop_table("ti_detail")
    op.drop_index(op.f("ix_sme_panel_created_at"), table_name="sme_panel")
    op.drop_table("sme_panel")
    op.drop_index(op.f("ix_sekolah_jenjang_pendidikan_id"), table_name="sekolah")
    op.drop_index(op.f("ix_sekolah_created_at"), table_name="sekolah")
    op.drop_table("sekolah")
    op.drop_index(op.f("ix_partisipan_sekolah_id"), table_name="partisipan")
    op.drop_index(op.f("ix_partisipan_jabatan_utama_id"), table_name="partisipan")
    op.drop_index(op.f("ix_partisipan_email"), table_name="partisipan")
    op.drop_index(op.f("ix_partisipan_created_at"), table_name="partisipan")
    op.drop_index(op.f("ix_partisipan_authentik_user_id"), table_name="partisipan")
    op.drop_table("partisipan")
    op.drop_table("mata_pelajaran")
    op.drop_table("jenjang_pendidikan")
    op.drop_index(op.f("ix_jabatan_unit_kerja_id"), table_name="jabatan")
    op.drop_index(op.f("ix_jabatan_created_at"), table_name="jabatan")
    op.drop_table("jabatan")
    op.drop_table("idempotency_keys")
    op.drop_table("dcs_subskala")
    op.drop_index(op.f("ix_dcs_sesi_created_at"), table_name="dcs_sesi")
    op.drop_table("dcs_sesi")
    op.drop_index(op.f("ix_dcs_responden_sesi_id"), table_name="dcs_responden")
    op.drop_index(op.f("ix_dcs_responden_partisipan_id"), table_name="dcs_responden")
    op.drop_index(op.f("ix_dcs_responden_created_at"), table_name="dcs_responden")
    op.drop_table("dcs_responden")
    op.drop_index(op.f("ix_dcs_jawaban_responden_id"), table_name="dcs_jawaban")
    op.drop_table("dcs_jawaban")
    op.drop_index(op.f("ix_dcs_item_subskala_kode"), table_name="dcs_item")
    op.drop_table("dcs_item")
    # ### end Alembic commands ###
