"""opm_sesi tambah kolom cabang, lepas keunikan global jabatan_id

Revision ID: 981b2e1945b0
Revises: c1eacaf37063
Create Date: 2026-08-03 13:13:42.228350

Backlog `anjab-abk-backend#37`. Sesi OPM sebelumnya unik per `jabatan_id` saja
(`OpmSesiModel.jabatan_id: unique=True`), sehingga satu jabatan hanya bisa punya
SATU sesi OPM — padahal sesi Task Inventory sumbernya sudah dibedakan per cabang
(`ti_sesi.cabang`, revisi `08b6b999ee05`) dan himpunan task terpilihnya berbeda
antar cabang. Akibatnya jabatan yang punya sesi TI Bandung DAN Semarang tak bisa
dibuatkan sesi OPM untuk cabang kedua — 409 palsu.

- **`ADD COLUMN opm_sesi.cabang VARCHAR(20) NULL`** — cermin `ti_sesi.cabang`.
  Diturunkan (bukan input) oleh `SqlOpmSesiService.create()` dari
  `ti_sesi.cabang` sesi TI sumber; nullable karena sesi TI sumber boleh
  ber-`cabang IS NULL` (sesi lama sebelum `08b6b999ee05`).
- **`DROP INDEX`/`CREATE INDEX ix_opm_sesi_jabatan_id` (unique=False)** — nama
  indeks dipertahankan (bukan drop lalu buat indeks baru dengan nama beda) agar
  `test_schema_matches_models` tetap cocok. Uniqueness `(jabatan_id, cabang)`
  yang baru ditegakkan di APLIKASI (`SqlOpmSesiService.create()`), BUKAN
  constraint DB — `cabang` nullable, dan PostgreSQL memperlakukan `NULL` sebagai
  distinct pada unique constraint, sehingga constraint DB tidak akan memblokir
  dua sesi ber-`cabang IS NULL` untuk jabatan yang sama (pre-check Python di
  service yang menutup celah itu).
- **Tidak ada `UPDATE`/`DELETE` di revisi ini** — backfill nilai `cabang` untuk
  3 sesi OPM produksi yang sudah ada (semuanya bersumber dari sesi TI cabang
  Semarang) ada di revisi TERPISAH setelah ini (disiplin satu perubahan/berkas).
- `downgrade()` mengembalikan indeks unik — **best-effort**: gagal berisik
  (`IntegrityError`) bila di database saat itu sudah ada >1 sesi OPM untuk
  jabatan yang sama (mengikuti konvensi downgrade repo ini, mis. `3b10e24fa970`).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "981b2e1945b0"
down_revision: str | None = "c1eacaf37063"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opm_sesi", sa.Column("cabang", sa.String(length=20), nullable=True))
    op.drop_index(op.f("ix_opm_sesi_jabatan_id"), table_name="opm_sesi")
    op.create_index(op.f("ix_opm_sesi_jabatan_id"), "opm_sesi", ["jabatan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_opm_sesi_jabatan_id"), table_name="opm_sesi")
    op.create_index(op.f("ix_opm_sesi_jabatan_id"), "opm_sesi", ["jabatan_id"], unique=True)
    op.drop_column("opm_sesi", "cabang")
    # ### end Alembic commands ###
