"""tambah kolom cabang ke sekolah

Revision ID: 3ae579a1e435
Revises: 983594126c4a
Create Date: 2026-09-08 15:37:52.578101

Backlog `anjab-abk-backend#40`. Murni DDL — satu kolom baru pada `sekolah`:
`cabang` (`String(20)`, nullable, tanpa server default). Sumber tunggal cabang
seorang PARTISIPAN, lewat `partisipan.sekolah_id` (lihat
`schemas/common.py::Cabang`) — nullable disengaja, "belum diketahui" tidak
boleh tertukar dengan "salah cabang". Backfill dari `sekolah.provinsi` untuk
baris existing ada di revisi data terpisah yang mengikuti revisi ini,
mengikuti disiplin migrasi repo ini: satu revisi = satu perubahan struktur,
backfill dipisah dari DDL (preseden `c8fb8be9e184`/`ad595b80d3d1`).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ae579a1e435"
down_revision: str | None = "983594126c4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sekolah", sa.Column("cabang", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sekolah", "cabang")
    # ### end Alembic commands ###
