"""tambah tabel usulan uraian tugas dari partisipan tahap 1

Revision ID: 92f6851d040c
Revises: 7c825d99216f
Create Date: 2026-07-26 08:56:45.167098

Backlog `anjab-abk-backend#26`. Tabel baru `ti_usulan_task` menampung usulan uraian
tugas yang dicatat responden Tahap 1 saat tugas yang ia kerjakan tidak ada di katalog
(`api/v1/taskinv_seleksi.py::valid_kodes_for_jabatan` hanya menerima `task_kode` yang
sudah ada). `tugas_pokok_id`/`detil_tugas_id` sengaja BUKAN `ForeignKey` — usulan tidak
menyentuh katalog master (`ti_uraian_tugas*`); nama induknya diresolusi live saat baca
(lihat `taskinv/services/usulan_sql.py`). Tanpa `UniqueConstraint` — dua orang boleh
mengusulkan tugas yang mirip, koordinator Tahap 2 yang memutuskan (`disetujui`).
Review & materialisasi `task_kode` ke katalog adalah item lanjutan terpisah (`#27`).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "92f6851d040c"
down_revision: str | None = "7c825d99216f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ti_usulan_task",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("tugas_pokok_id", sa.String(length=40), nullable=False),
        sa.Column("detil_tugas_id", sa.String(length=40), nullable=True),
        sa.Column("uraian", sa.Text(), nullable=False),
        sa.Column("disetujui", sa.Boolean(), nullable=True),
        sa.Column("task_kode", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["responden_id"],
            ["ti_responden.id"],
            name=op.f("fk_ti_usulan_task_responden_id_ti_responden"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sesi_id"],
            ["ti_sesi.id"],
            name=op.f("fk_ti_usulan_task_sesi_id_ti_sesi"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_usulan_task")),
    )
    op.create_index(
        op.f("ix_ti_usulan_task_created_at"), "ti_usulan_task", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ti_usulan_task_responden_id"), "ti_usulan_task", ["responden_id"], unique=False
    )
    op.create_index(op.f("ix_ti_usulan_task_sesi_id"), "ti_usulan_task", ["sesi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ti_usulan_task_sesi_id"), table_name="ti_usulan_task")
    op.drop_index(op.f("ix_ti_usulan_task_responden_id"), table_name="ti_usulan_task")
    op.drop_index(op.f("ix_ti_usulan_task_created_at"), table_name="ti_usulan_task")
    op.drop_table("ti_usulan_task")
    # ### end Alembic commands ###
