"""uraian tugas m2m via association object

Revision ID: 7c825d99216f
Revises: fd3dd550aa99
Create Date: 2026-07-25 20:46:57.543032

Pisah `TiUraianTugasModel` (dulu memikul `kode`/`unit`/`jabatan_id`/`urutan`/
`tugas_pokok_id`/`detil_tugas_id`/`std_*` langsung, relasi 1:N ke jabatan) menjadi
entitas kanonik (hanya `id`/`uraian`/`created_at`) + association object baru
`TiUraianTugasJabatanModel` (`ti_uraian_tugas_jabatan`) yang memikul seluruh atribut
per-jabatan. Migrasi ini 1:1 NON-LOSSY: setiap baris `ti_uraian_tugas` lama menjadi
tepat satu baris kanonik (tidak berubah) + tepat satu baris link baru. Tidak ada
dedup/kanonikalisasi baris `uraian` yang teksnya identik — itu pekerjaan terpisah
yang menyusul (lihat backlog `anjab-abk-backend#23`).

Urutan `upgrade()`: (1) buat tabel `ti_uraian_tugas_jabatan`; (2) `INSERT ... SELECT`
memindahkan kolom per-jabatan dari `ti_uraian_tugas` ke baris link baru (satu link per
baris kanonik, `uraian_tugas_id` = `id` lama); (3) drop kolom yang sudah pindah +
index/unique constraint `kode` lama dari `ti_uraian_tugas`.

`downgrade()` merekonstruksi PENUH (bukan best-effort kosong) — data yang dipindah
masih utuh di `ti_uraian_tugas_jabatan` sampai tabel itu di-drop di langkah terakhir,
jadi kolom lama diisi kembali dari situ (`UPDATE ... FROM ...`) sebelum tabel link
dihapus.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7c825d99216f"
down_revision: str | None = "fd3dd550aa99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_LINK_COLUMNS = (
    "kode",
    "jabatan_id",
    "unit",
    "urutan",
    "tugas_pokok_id",
    "detil_tugas_id",
    "std_sumber_bukti",
    "std_kondisi",
    "std_frekuensi_teks",
    "std_durasi_per_kali",
    "std_jam_per_minggu",
    "std_peak4w_hours",
    "std_va_type",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ti_uraian_tugas_jabatan",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uraian_tugas_id", sa.String(length=40), nullable=False),
        sa.Column("kode", sa.String(length=20), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.Column("tugas_pokok_id", sa.String(length=40), nullable=False),
        sa.Column("detil_tugas_id", sa.String(length=40), nullable=True),
        sa.Column("std_sumber_bukti", sa.String(length=20), nullable=True),
        sa.Column("std_kondisi", sa.String(length=20), nullable=True),
        sa.Column("std_frekuensi_teks", sa.String(length=100), nullable=True),
        sa.Column("std_durasi_per_kali", sa.String(length=100), nullable=True),
        sa.Column("std_jam_per_minggu", sa.Float(), nullable=True),
        sa.Column("std_peak4w_hours", sa.Float(), nullable=True),
        sa.Column("std_va_type", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(
            ["uraian_tugas_id"],
            ["ti_uraian_tugas.id"],
            name=op.f("fk_ti_uraian_tugas_jabatan_uraian_tugas_id_ti_uraian_tugas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ti_uraian_tugas_jabatan")),
        sa.UniqueConstraint("kode", name=op.f("uq_ti_uraian_tugas_jabatan_kode")),
        sa.UniqueConstraint(
            "uraian_tugas_id", "jabatan_id", name=op.f("uq_ti_uraian_tugas_jabatan_uraian_tugas_id")
        ),
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_detil_tugas_id"),
        "ti_uraian_tugas_jabatan",
        ["detil_tugas_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_jabatan_id"),
        "ti_uraian_tugas_jabatan",
        ["jabatan_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_tugas_pokok_id"),
        "ti_uraian_tugas_jabatan",
        ["tugas_pokok_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_unit"), "ti_uraian_tugas_jabatan", ["unit"], unique=False
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_uraian_tugas_id"),
        "ti_uraian_tugas_jabatan",
        ["uraian_tugas_id"],
        unique=False,
    )

    # Pindahkan data non-lossy: 1 baris ti_uraian_tugas lama -> 1 baris kanonik
    # (tidak berubah) + 1 baris link baru (uraian_tugas_id = id lama).
    op.get_bind().execute(
        sa.text(
            f"""
            INSERT INTO ti_uraian_tugas_jabatan
                (uraian_tugas_id, {", ".join(_LINK_COLUMNS)})
            SELECT id, {", ".join(_LINK_COLUMNS)}
            FROM ti_uraian_tugas
            """
        )
    )

    op.drop_index(op.f("ix_ti_uraian_tugas_detil_tugas_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_jabatan_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_tugas_pokok_id"), table_name="ti_uraian_tugas")
    op.drop_index(op.f("ix_ti_uraian_tugas_unit"), table_name="ti_uraian_tugas")
    op.drop_constraint(op.f("uq_ti_uraian_tugas_kode"), "ti_uraian_tugas", type_="unique")
    op.drop_column("ti_uraian_tugas", "std_va_type")
    op.drop_column("ti_uraian_tugas", "tugas_pokok_id")
    op.drop_column("ti_uraian_tugas", "std_durasi_per_kali")
    op.drop_column("ti_uraian_tugas", "std_jam_per_minggu")
    op.drop_column("ti_uraian_tugas", "kode")
    op.drop_column("ti_uraian_tugas", "std_frekuensi_teks")
    op.drop_column("ti_uraian_tugas", "std_peak4w_hours")
    op.drop_column("ti_uraian_tugas", "std_kondisi")
    op.drop_column("ti_uraian_tugas", "urutan")
    op.drop_column("ti_uraian_tugas", "jabatan_id")
    op.drop_column("ti_uraian_tugas", "unit")
    op.drop_column("ti_uraian_tugas", "std_sumber_bukti")
    op.drop_column("ti_uraian_tugas", "detil_tugas_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("detil_tugas_id", sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_sumber_bukti", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    # nullable=True SEMENTARA (target akhir NOT NULL) — kolom diisi via UPDATE...FROM
    # di bawah sebelum di-ALTER SET NOT NULL; menghindari gagal ADD COLUMN NOT NULL
    # pada tabel berisi baris (konvensi sama dengan `fd3dd550aa99`).
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("unit", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("jabatan_id", sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas", sa.Column("urutan", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_kondisi", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column(
            "std_peak4w_hours",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_frekuensi_teks", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("kode", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column(
            "std_jam_per_minggu",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column(
            "std_durasi_per_kali", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("tugas_pokok_id", sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_va_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )

    # Rekonstruksi PENUH dari ti_uraian_tugas_jabatan — data masih utuh di sana
    # sampai tabel itu di-drop di akhir fungsi ini.
    op.get_bind().execute(
        sa.text(
            f"""
            UPDATE ti_uraian_tugas t
            SET {", ".join(f"{col} = l.{col}" for col in _LINK_COLUMNS)}
            FROM ti_uraian_tugas_jabatan l
            WHERE l.uraian_tugas_id = t.id
            """
        )
    )

    # Kembalikan NOT NULL untuk kolom yang semula wajib.
    op.alter_column("ti_uraian_tugas", "kode", nullable=False)
    op.alter_column("ti_uraian_tugas", "unit", nullable=False)
    op.alter_column("ti_uraian_tugas", "jabatan_id", nullable=False)
    op.alter_column("ti_uraian_tugas", "urutan", nullable=False)
    op.alter_column("ti_uraian_tugas", "tugas_pokok_id", nullable=False)

    op.create_unique_constraint(
        op.f("uq_ti_uraian_tugas_kode"),
        "ti_uraian_tugas",
        ["kode"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_ti_uraian_tugas_unit"), "ti_uraian_tugas", ["unit"], unique=False)
    op.create_index(
        op.f("ix_ti_uraian_tugas_tugas_pokok_id"),
        "ti_uraian_tugas",
        ["tugas_pokok_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_jabatan_id"), "ti_uraian_tugas", ["jabatan_id"], unique=False
    )
    op.create_index(
        op.f("ix_ti_uraian_tugas_detil_tugas_id"),
        "ti_uraian_tugas",
        ["detil_tugas_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_ti_uraian_tugas_jabatan_uraian_tugas_id"), table_name="ti_uraian_tugas_jabatan"
    )
    op.drop_index(op.f("ix_ti_uraian_tugas_jabatan_unit"), table_name="ti_uraian_tugas_jabatan")
    op.drop_index(
        op.f("ix_ti_uraian_tugas_jabatan_tugas_pokok_id"), table_name="ti_uraian_tugas_jabatan"
    )
    op.drop_index(
        op.f("ix_ti_uraian_tugas_jabatan_jabatan_id"), table_name="ti_uraian_tugas_jabatan"
    )
    op.drop_index(
        op.f("ix_ti_uraian_tugas_jabatan_detil_tugas_id"), table_name="ti_uraian_tugas_jabatan"
    )
    op.drop_table("ti_uraian_tugas_jabatan")
    # ### end Alembic commands ###
