"""tambah nilai standar OPM ke snapshot opm_sesi_task

Revision ID: c1eacaf37063
Revises: ad595b80d3d1
Create Date: 2026-07-29 03:20:52.488083

Backlog `anjab-abk-backend#34`, lanjutan langsung `#33` (`c8fb8be9e184`/`ad595b80d3d1`).
Murni DDL — tiga kolom baru pada `opm_sesi_task`: `std_importance`, `std_frequency`,
`std_criticality` (`Integer`, nullable, tanpa server default). Diisi oleh
`SqlOpmSesiService.create()` yang MENYALIN nilai dari `ti_uraian_tugas_jabatan.std_opm_*`
pada saat sesi OPM dibuat — nilai beku, tidak pernah disegarkan ulang. Tanpa prefiks
`opm_` karena tabel ini sudah milik domain OPM (beda dari katalog TI yang perlu
`std_opm_` untuk membedakannya dari `std_frekuensi_teks`). Tidak ada migrasi data:
sesi OPM produksi saat ini nol baris (diverifikasi via MCP `daftar_opm_sesi`,
`total: 0`), jadi tidak ada baris `opm_sesi_task` existing yang perlu di-backfill.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c1eacaf37063"
down_revision: str | None = "ad595b80d3d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("opm_sesi_task", sa.Column("std_importance", sa.Integer(), nullable=True))
    op.add_column("opm_sesi_task", sa.Column("std_frequency", sa.Integer(), nullable=True))
    op.add_column("opm_sesi_task", sa.Column("std_criticality", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("opm_sesi_task", "std_criticality")
    op.drop_column("opm_sesi_task", "std_frequency")
    op.drop_column("opm_sesi_task", "std_importance")
    # ### end Alembic commands ###
