"""longgarkan kolom calhr ti_detail agar nullable

Backlog `anjab-abk-backend#38`: draft parsial Tahap 3 (`PUT .../detail`) harus bisa
disimpan sebelum kelima field CalHR (`sumber_bukti`/`kondisi`/`frekuensi_teks`/
`durasi_per_kali`/`va_type`) terisi lengkap — kelengkapan digerbang saat
`POST .../detail/submit` (`TiDetailService.submit`), bukan lagi di setiap PUT. Tanpa
migrasi data: seluruh baris `ti_detail` existing sudah terisi penuh (kelima kolom NOT
NULL sebelumnya), jadi tidak ada backfill yang diperlukan.

`downgrade()` mengembalikan `NOT NULL` apa adanya dan akan GAGAL bila saat itu ada baris
ber-NULL pada salah satu kolom — disengaja, mengikuti konvensi downgrade best-effort
repo ini (bandingkan `fd3dd550aa99`, `08b6b999ee05`).

Revision ID: 983594126c4a
Revises: 25dba11a0c55
Create Date: 2026-08-07 06:27:49.528945
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "983594126c4a"
down_revision: str | None = "25dba11a0c55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ti_detail", "sumber_bukti", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column("ti_detail", "kondisi", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column(
        "ti_detail", "frekuensi_teks", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("ti_detail", "durasi_per_kali", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("ti_detail", "va_type", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ti_detail", "va_type", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("ti_detail", "durasi_per_kali", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "ti_detail", "frekuensi_teks", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("ti_detail", "kondisi", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column(
        "ti_detail", "sumber_bukti", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###
