"""tambah nilai standar calhr di uraian tugas & flag setuju di ti_detail

Revision ID: 0c932069e90e
Revises: a4aeb5bcbe81
Create Date: 2026-07-12 05:08:32.131090

Master `ti_uraian_tugas` mendapat 9 kolom `std_*` (prefix penanda "nilai standar")
yang menampung nilai standar CalHR — dipakai untuk mem-prefill form partisipan di
Tahap 3 sehingga ia cukup menyatakan setuju alih-alih mengisi dari nol. Semua kolom
`std_*` nullable: master lama tanpa nilai standar tetap valid, dan task tanpa standar
membuat Tahap 3 berperilaku persis seperti sebelum revisi ini (isian kosong).

`ti_detail` mendapat kolom `setuju_standar` (boolean, default `true`) yang merekam
apakah partisipan menerima nilai standar apa adanya atau mengubah minimal satu
komponen. `server_default=true` membuat baris lama otomatis `setuju_standar = true`
(tidak ada standar untuk dibantah saat baris itu dibuat).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0c932069e90e"
down_revision: str | None = "a4aeb5bcbe81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ti_detail",
        sa.Column("setuju_standar", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    op.add_column(
        "ti_uraian_tugas", sa.Column("std_sumber_bukti", sa.String(length=20), nullable=True)
    )
    op.add_column("ti_uraian_tugas", sa.Column("std_kondisi", sa.String(length=20), nullable=True))
    op.add_column(
        "ti_uraian_tugas", sa.Column("std_frekuensi_teks", sa.String(length=100), nullable=True)
    )
    op.add_column("ti_uraian_tugas", sa.Column("std_durasi_per_kali", sa.Integer(), nullable=True))
    op.add_column("ti_uraian_tugas", sa.Column("std_jam_per_minggu", sa.Float(), nullable=True))
    op.add_column("ti_uraian_tugas", sa.Column("std_peak4w_hours", sa.Float(), nullable=True))
    op.add_column("ti_uraian_tugas", sa.Column("std_ai_mode", sa.String(length=20), nullable=True))
    op.add_column("ti_uraian_tugas", sa.Column("std_va_type", sa.String(length=20), nullable=True))
    op.add_column("ti_uraian_tugas", sa.Column("std_dcs_flag", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ti_uraian_tugas", "std_dcs_flag")
    op.drop_column("ti_uraian_tugas", "std_va_type")
    op.drop_column("ti_uraian_tugas", "std_ai_mode")
    op.drop_column("ti_uraian_tugas", "std_peak4w_hours")
    op.drop_column("ti_uraian_tugas", "std_jam_per_minggu")
    op.drop_column("ti_uraian_tugas", "std_durasi_per_kali")
    op.drop_column("ti_uraian_tugas", "std_frekuensi_teks")
    op.drop_column("ti_uraian_tugas", "std_kondisi")
    op.drop_column("ti_uraian_tugas", "std_sumber_bukti")
    op.drop_column("ti_detail", "setuju_standar")
    # ### end Alembic commands ###
