"""hapus ai_mode dcs_flag dari calhr

Revision ID: fd3dd550aa99
Revises: 08b6b999ee05
Create Date: 2026-07-15 03:29:39.569344
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fd3dd550aa99"
down_revision: str | None = "08b6b999ee05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ti_detail", "dcs_flag")
    op.drop_column("ti_detail", "ai_mode")
    op.drop_column("ti_uraian_tugas", "std_ai_mode")
    op.drop_column("ti_uraian_tugas", "std_dcs_flag")
    # ### end Alembic commands ###


def downgrade() -> None:
    # Downgrade best-effort: kolom dikembalikan, tapi nilai lama (dihapus di upgrade())
    # TIDAK direkonstruksi. `ti_detail.ai_mode`/`dcs_flag` semula NOT NULL tanpa
    # server_default — tabel berisi butuh server_default sementara agar ADD COLUMN tak
    # gagal, konsisten dengan konvensi downgrade best-effort di repo (mis. `3b10e24fa970`).
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_dcs_flag", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_uraian_tugas",
        sa.Column("std_ai_mode", sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    )
    op.add_column(
        "ti_detail",
        sa.Column(
            "ai_mode",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            server_default="Human-led",
        ),
    )
    op.add_column(
        "ti_detail",
        sa.Column(
            "dcs_flag",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column("ti_detail", "ai_mode", server_default=None)
    op.alter_column("ti_detail", "dcs_flag", server_default=None)
    # ### end Alembic commands ###
