"""opm jawaban tiga dimensi jadi nullable

Backlog `anjab-abk-backend#39`: draft rating OPM (`PUT .../jawaban`) harus bisa
disimpan sebelum ketiga dimensi CalHR (`importance`/`frequency`/`criticality`) terisi
lengkap — kelengkapan digerbang saat `POST .../jawaban/submit` (`OpmJawabanService.submit`),
bukan lagi di setiap PUT. Tanpa migrasi data: `opm_sesi` produksi saat ini nol baris,
jadi tidak ada baris `opm_jawaban` existing yang perlu di-backfill.

`downgrade()` mengembalikan `NOT NULL` apa adanya dan akan GAGAL bila saat itu ada baris
ber-NULL pada salah satu kolom — disengaja, mengikuti konvensi downgrade best-effort
repo ini (bandingkan `983594126c4a`, `fd3dd550aa99`).

Revision ID: 25dba11a0c55
Revises: 983594126c4a
Create Date: 2026-08-07 06:28:21.102215
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "25dba11a0c55"
down_revision: str | None = "983594126c4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("opm_jawaban", "importance", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("opm_jawaban", "frequency", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("opm_jawaban", "criticality", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("opm_jawaban", "criticality", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("opm_jawaban", "frequency", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("opm_jawaban", "importance", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
