"""tambah tabel opm sesi task responden jawaban

Revision ID: c822a30d6b39
Revises: d3e6f1a8b9c2
Create Date: 2026-07-02 01:41:30.092062
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c822a30d6b39"
down_revision: str | None = "d3e6f1a8b9c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "opm_jawaban",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("responden_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opm_jawaban")),
        sa.UniqueConstraint("responden_id", "task_kode", name=op.f("uq_opm_jawaban_responden_id")),
    )
    op.create_index(
        op.f("ix_opm_jawaban_responden_id"), "opm_jawaban", ["responden_id"], unique=False
    )
    op.create_table(
        "opm_responden",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("nama", sa.String(length=200), nullable=True),
        sa.Column("jabatan_label", sa.String(length=200), nullable=False),
        sa.Column("partisipan_id", sa.String(length=40), nullable=True),
        sa.Column("sudah_submit", sa.Boolean(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opm_responden")),
    )
    op.create_index(
        op.f("ix_opm_responden_created_at"), "opm_responden", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_opm_responden_partisipan_id"), "opm_responden", ["partisipan_id"], unique=False
    )
    op.create_index(op.f("ix_opm_responden_sesi_id"), "opm_responden", ["sesi_id"], unique=False)
    op.create_table(
        "opm_sesi",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("jabatan_id", sa.String(length=40), nullable=False),
        sa.Column("ti_sesi_id", sa.String(length=40), nullable=False),
        sa.Column("periode", sa.String(length=7), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("min_responden", sa.Integer(), nullable=False),
        sa.Column("max_responden", sa.Integer(), nullable=False),
        sa.Column("catatan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opm_sesi")),
    )
    op.create_index(op.f("ix_opm_sesi_created_at"), "opm_sesi", ["created_at"], unique=False)
    op.create_index(op.f("ix_opm_sesi_jabatan_id"), "opm_sesi", ["jabatan_id"], unique=True)
    op.create_table(
        "opm_sesi_task",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sesi_id", sa.String(length=40), nullable=False),
        sa.Column("task_kode", sa.String(length=20), nullable=False),
        sa.Column("uraian_tugas", sa.Text(), nullable=False),
        sa.Column("tugas_pokok", sa.String(length=300), nullable=False),
        sa.Column("detil_tugas", sa.String(length=300), nullable=True),
        sa.Column("urutan", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sesi_id"],
            ["opm_sesi.id"],
            name=op.f("fk_opm_sesi_task_sesi_id_opm_sesi"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opm_sesi_task")),
        sa.UniqueConstraint("sesi_id", "task_kode", name=op.f("uq_opm_sesi_task_sesi_id")),
    )
    op.create_index(op.f("ix_opm_sesi_task_sesi_id"), "opm_sesi_task", ["sesi_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_opm_sesi_task_sesi_id"), table_name="opm_sesi_task")
    op.drop_table("opm_sesi_task")
    op.drop_index(op.f("ix_opm_sesi_jabatan_id"), table_name="opm_sesi")
    op.drop_index(op.f("ix_opm_sesi_created_at"), table_name="opm_sesi")
    op.drop_table("opm_sesi")
    op.drop_index(op.f("ix_opm_responden_sesi_id"), table_name="opm_responden")
    op.drop_index(op.f("ix_opm_responden_partisipan_id"), table_name="opm_responden")
    op.drop_index(op.f("ix_opm_responden_created_at"), table_name="opm_responden")
    op.drop_table("opm_responden")
    op.drop_index(op.f("ix_opm_jawaban_responden_id"), table_name="opm_jawaban")
    op.drop_table("opm_jawaban")
    # ### end Alembic commands ###
