"""Agregasi router dengan prefix versi `/api/v1`."""

from __future__ import annotations

from fastapi import APIRouter

from .v1 import (
    dcs_hasil,
    dcs_kuesioner,
    dcs_responden,
    dcs_sesi,
    dcs_subskala,
    jabatan,
    jenjang_pendidikan,
    mata_pelajaran,
    partisipan,
    sekolah,
    sme_panel,
    system,
    taskinv_catalog,
    taskinv_detail,
    taskinv_detil_tugas,
    taskinv_hasil,
    taskinv_kuesioner,
    taskinv_responden,
    taskinv_seleksi,
    taskinv_sesi,
    taskinv_tahap2,
    taskinv_tugas_pokok,
    taskinv_uraian_tugas,
    ts_kuesioner,
    ts_log,
    ts_responden,
    ts_sesi,
    wcp_dimensi,
    wcp_hasil,
    wcp_kuesioner,
    wcp_responden,
    wcp_sesi,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(system.router, tags=["system"])
api_router.include_router(
    jenjang_pendidikan.router,
    prefix="/jenjang-pendidikan",
    tags=["core.jenjang-pendidikan"],
)
api_router.include_router(
    sekolah.router,
    prefix="/sekolah",
    tags=["core.sekolah"],
)
api_router.include_router(
    mata_pelajaran.router,
    prefix="/mata-pelajaran",
    tags=["core.mata-pelajaran"],
)
api_router.include_router(
    partisipan.router,
    prefix="/partisipan",
    tags=["core.partisipan"],
)
api_router.include_router(
    jabatan.router,
    prefix="/jabatan",
    tags=["anjab.jabatan"],
)
api_router.include_router(
    sme_panel.router,
    prefix="/sme-panel",
    tags=["anjab.sme-panel"],
)
api_router.include_router(
    dcs_kuesioner.router,
    prefix="/dcs",
    tags=["dcs.kuesioner"],
)
api_router.include_router(
    wcp_kuesioner.router,
    prefix="/wcp",
    tags=["wcp.kuesioner"],
)
api_router.include_router(
    wcp_dimensi.router,
    prefix="/wcp/dimensi",
    tags=["wcp.dimensi"],
)
api_router.include_router(
    wcp_sesi.router,
    prefix="/wcp/sesi",
    tags=["wcp.sesi"],
)
api_router.include_router(
    wcp_responden.router,
    prefix="/wcp/sesi",
    tags=["wcp.responden"],
)
api_router.include_router(
    wcp_hasil.router,
    prefix="/wcp/sesi",
    tags=["wcp.hasil"],
)
api_router.include_router(
    dcs_subskala.router,
    prefix="/dcs/sub-skala",
    tags=["dcs.sub-skala"],
)
api_router.include_router(
    dcs_sesi.router,
    prefix="/dcs/sesi",
    tags=["dcs.sesi"],
)
api_router.include_router(
    dcs_responden.router,
    prefix="/dcs/sesi",
    tags=["dcs.responden"],
)
api_router.include_router(
    dcs_hasil.router,
    prefix="/dcs/sesi",
    tags=["dcs.hasil"],
)
api_router.include_router(
    taskinv_kuesioner.router,
    prefix="/task-inventory",
    tags=["taskinv.kuesioner"],
)
api_router.include_router(
    taskinv_catalog.router,
    prefix="/task-inventory/catalog",
    tags=["taskinv.catalog"],
)
api_router.include_router(
    taskinv_sesi.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.sesi"],
)
api_router.include_router(
    taskinv_responden.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.responden"],
)
api_router.include_router(
    taskinv_seleksi.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.seleksi"],
)
api_router.include_router(
    taskinv_detail.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.detail"],
)
api_router.include_router(
    taskinv_tahap2.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.tahap2"],
)
api_router.include_router(
    taskinv_hasil.router,
    prefix="/task-inventory/sesi",
    tags=["taskinv.hasil"],
)
api_router.include_router(
    ts_kuesioner.router,
    prefix="/time-study",
    tags=["ts.kuesioner"],
)
api_router.include_router(
    ts_sesi.router,
    prefix="/time-study/sesi",
    tags=["ts.sesi"],
)
api_router.include_router(
    ts_responden.router,
    prefix="/time-study/sesi",
    tags=["ts.responden"],
)
api_router.include_router(
    ts_log.router,
    prefix="/time-study/responden",
    tags=["ts.log"],
)
api_router.include_router(
    taskinv_tugas_pokok.router,
    prefix="/task-inventory/tugas-pokok",
    tags=["taskinv.tugas-pokok"],
)
api_router.include_router(
    taskinv_detil_tugas.router,
    prefix="/task-inventory/detil-tugas",
    tags=["taskinv.detil-tugas"],
)
api_router.include_router(
    taskinv_uraian_tugas.router,
    prefix="/task-inventory/uraian-tugas",
    tags=["taskinv.uraian-tugas"],
)
